"""rename id_lokasi to lokasi_penimbangan in TTbsDalam

Revision ID: 60f9d711d993
Revises: 21732458bdb4
Create Date: 2025-10-17 14:02:36.210992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60f9d711d993'
down_revision: Union[str, None] = '21732458bdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # hanya rename kolom, tanpa membuat tabel baru
    with op.batch_alter_table('TTbsDalam', schema=None) as batch_op:
        batch_op.alter_column('id_lokasi', new_column_name='lokasi_timbang', existing_type=sa.String(100))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TTbsDalam', schema=None) as batch_op:
        batch_op.alter_column('lokasi_timbang', new_column_name='id_lokasi', existing_type=sa.Integer())
    # ### end Alembic commands ###
