"""setup for migration

Revision ID: b5015e702e09
Revises: b69d8b6ed505
Create Date: 2025-10-23 10:10:32.173048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5015e702e09'
down_revision: Union[str, None] = 'b69d8b6ed505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MLokasi',
    sa.Column('id_lokasi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_lokasi', sa.String(length=20), nullable=False),
    sa.Column('nama_lokasi', sa.String(length=100), nullable=False),
    sa.Column('distrik', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.String(length=50), nullable=True),
    sa.Column('alamat', sa.String(length=200), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_lokasi'),
    sa.UniqueConstraint('kode_lokasi')
    )
    op.create_table('TTbsDalam',
    sa.Column('NoTransaksi', sa.String(length=100), nullable=False),
    sa.Column('PlatNo', sa.String(length=50), nullable=True),
    sa.Column('NamaDriver', sa.String(length=100), nullable=True),
    sa.Column('NamaProduk', sa.String(length=100), nullable=True),
    sa.Column('TglTransaksiOne', sa.Date(), nullable=True),
    sa.Column('TimeTmbOne', sa.Time(), nullable=True),
    sa.Column('TmbOne', sa.Integer(), nullable=True),
    sa.Column('TglTransaksiTwo', sa.Date(), nullable=True),
    sa.Column('TimeTmbTwo', sa.Time(), nullable=True),
    sa.Column('TmbTwo', sa.Integer(), nullable=True),
    sa.Column('NamaKebun', sa.String(length=50), nullable=True),
    sa.Column('Divisi', sa.String(length=50), nullable=True),
    sa.Column('JumlahJanjang', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('NamaPT', sa.String(length=50), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.Column('TotalPot', sa.Integer(), nullable=True),
    sa.Column('BJR', sa.Integer(), nullable=True),
    sa.Column('JenisTbs', sa.String(length=50), nullable=True),
    sa.Column('lokasi_penimbangan', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi')
    )
    op.create_index(op.f('ix_TTbsDalam_NoTransaksi'), 'TTbsDalam', ['NoTransaksi'], unique=False)
    op.create_table('TTransLintas',
    sa.Column('NoTransaksi', sa.String(length=50), nullable=False),
    sa.Column('NoDO', sa.String(length=50), nullable=True),
    sa.Column('NamaProduk', sa.String(length=50), nullable=True),
    sa.Column('TglTmb1', sa.Date(), nullable=True),
    sa.Column('TimeTmb1', sa.Time(), nullable=True),
    sa.Column('Tmb1', sa.Integer(), nullable=True),
    sa.Column('TglTmb2', sa.Date(), nullable=True),
    sa.Column('TimeTmb2', sa.Time(), nullable=True),
    sa.Column('Tmb2', sa.Integer(), nullable=True),
    sa.Column('Qty', sa.Integer(), nullable=True),
    sa.Column('Terkirim', sa.Integer(), nullable=True),
    sa.Column('Diterima', sa.Integer(), nullable=True),
    sa.Column('Sisa', sa.Integer(), nullable=True),
    sa.Column('Transportir', sa.String(length=50), nullable=True),
    sa.Column('PlatNo', sa.String(length=50), nullable=True),
    sa.Column('NamaDriver', sa.String(length=50), nullable=True),
    sa.Column('NoSurat', sa.String(length=50), nullable=True),
    sa.Column('TglSurat', sa.Date(), nullable=True),
    sa.Column('Ket', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.Column('Tujuan', sa.String(length=50), nullable=True),
    sa.Column('id_lokasi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi')
    )
    op.create_index(op.f('ix_TTransLintas_NoTransaksi'), 'TTransLintas', ['NoTransaksi'], unique=False)
    op.create_table('TTransLintasKeluar',
    sa.Column('NoTransaksi', sa.String(length=50), nullable=False),
    sa.Column('NoDO', sa.String(length=50), nullable=True),
    sa.Column('NamaProduk', sa.String(length=50), nullable=True),
    sa.Column('TglTmb1', sa.Date(), nullable=True),
    sa.Column('TimeTmb1', sa.Time(), nullable=True),
    sa.Column('Tmb1', sa.Integer(), nullable=True),
    sa.Column('TglTmb2', sa.Date(), nullable=True),
    sa.Column('TimeTmb2', sa.Time(), nullable=True),
    sa.Column('Tmb2', sa.Integer(), nullable=True),
    sa.Column('Qty', sa.Integer(), nullable=True),
    sa.Column('Terkirim', sa.Integer(), nullable=True),
    sa.Column('Diterima', sa.Integer(), nullable=True),
    sa.Column('Sisa', sa.Integer(), nullable=True),
    sa.Column('Transportir', sa.String(length=50), nullable=True),
    sa.Column('PlatNo', sa.String(length=50), nullable=True),
    sa.Column('NamaDriver', sa.String(length=50), nullable=True),
    sa.Column('NoSurat', sa.String(length=50), nullable=True),
    sa.Column('TglSurat', sa.Date(), nullable=True),
    sa.Column('Ket', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.Column('Tujuan', sa.String(length=50), nullable=True),
    sa.Column('NoSegel', sa.String(length=50), nullable=True),
    sa.Column('JumlahSegel', sa.String(length=50), nullable=True),
    sa.Column('Asal', sa.String(length=50), nullable=True),
    sa.Column('Divisi', sa.String(length=50), nullable=True),
    sa.Column('JumlahJjg', sa.String(length=50), nullable=True),
    sa.Column('BJR', sa.String(length=50), nullable=True),
    sa.Column('id_lokasi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi')
    )
    op.create_index(op.f('ix_TTransLintasKeluar_NoTransaksi'), 'TTransLintasKeluar', ['NoTransaksi'], unique=False)
    op.create_table('TTransPemasaran',
    sa.Column('NoTransaksi', sa.String(length=50), nullable=False),
    sa.Column('NoDO', sa.String(length=50), nullable=True),
    sa.Column('NamaProduk', sa.String(length=50), nullable=True),
    sa.Column('TglTmb1', sa.Date(), nullable=True),
    sa.Column('TimeTmb1', sa.Time(), nullable=True),
    sa.Column('Tmb1', sa.Float(), nullable=True),
    sa.Column('TglTmb2', sa.Date(), nullable=True),
    sa.Column('TimeTmb2', sa.Time(), nullable=True),
    sa.Column('Tmb2', sa.Float(), nullable=True),
    sa.Column('Qty', sa.Float(), nullable=True),
    sa.Column('Terkirim', sa.Float(), nullable=True),
    sa.Column('Diterima', sa.Float(), nullable=True),
    sa.Column('Sisa', sa.Float(), nullable=True),
    sa.Column('Transportir', sa.String(length=100), nullable=True),
    sa.Column('PlatNO', sa.String(length=20), nullable=True),
    sa.Column('NamaDriver', sa.String(length=50), nullable=True),
    sa.Column('BeratTarra', sa.Float(), nullable=True),
    sa.Column('KadarKotoran', sa.Float(), nullable=True),
    sa.Column('KadarAir', sa.Float(), nullable=True),
    sa.Column('Moisture', sa.Float(), nullable=True),
    sa.Column('FFA', sa.Float(), nullable=True),
    sa.Column('IV', sa.Float(), nullable=True),
    sa.Column('SUHU', sa.Float(), nullable=True),
    sa.Column('NoTangki', sa.String(length=30), nullable=True),
    sa.Column('NoSegel', sa.String(length=50), nullable=True),
    sa.Column('JmlSegel', sa.Integer(), nullable=True),
    sa.Column('NoBlangko', sa.String(length=50), nullable=True),
    sa.Column('Pemeriksa', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('Asal', sa.String(length=100), nullable=True),
    sa.Column('Tujuan', sa.String(length=100), nullable=True),
    sa.Column('NoRef', sa.String(length=100), nullable=True),
    sa.Column('TotalTmb', sa.Float(), nullable=True),
    sa.Column('StatusSambungDO', sa.String(length=50), nullable=True),
    sa.Column('NoSambungDO', sa.String(length=50), nullable=True),
    sa.Column('id_lokasi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi')
    )
    op.create_index(op.f('ix_TTransPemasaran_NoTransaksi'), 'TTransPemasaran', ['NoTransaksi'], unique=False)
    op.drop_index('idx_ttranspemasaran_tgltmb1', table_name='ttranspemasaran')
    op.drop_table('ttranspemasaran')
    op.drop_table('ttranslintas')
    op.drop_index('kode_lokasi', table_name='mlokasi')
    op.drop_table('mlokasi')
    op.drop_index('idx_namakebun_tbsdalam', table_name='ttbsdalam')
    op.drop_index('idx_tgltransaksi_namakebun', table_name='ttbsdalam')
    op.drop_index('idx_tgltransaksi_tbsdalam', table_name='ttbsdalam')
    op.drop_index('idx_tgltransaksione', table_name='ttbsdalam')
    op.drop_table('ttbsdalam')
    op.drop_table('ttranslintaskeluar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ttranslintaskeluar',
    sa.Column('NoTransaksi', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('NoDO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaProduk', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TglTmb1', sa.DATE(), nullable=True),
    sa.Column('TimeTmb1', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TglTmb2', sa.DATE(), nullable=True),
    sa.Column('TimeTmb2', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Terkirim', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Diterima', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sisa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Transportir', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PlatNo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaDriver', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoSurat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TglSUrat', sa.DATE(), nullable=True),
    sa.Column('Ket', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_lokasi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Tujuan', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoSegel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('JumlahSegel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Asal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Divisi', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('JumlahJjg', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BJR', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ttbsdalam',
    sa.Column('NoTransaksi', mysql.LONGTEXT(), nullable=False),
    sa.Column('PlatNo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaDriver', mysql.LONGTEXT(), nullable=True),
    sa.Column('NamaProduk', mysql.LONGTEXT(), nullable=True),
    sa.Column('TglTransaksiOne', sa.DATE(), nullable=True),
    sa.Column('TimeTmbOne', mysql.TIME(fsp=6), nullable=True),
    sa.Column('TmbOne', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TglTransaksiTwo', sa.DATE(), nullable=True),
    sa.Column('TimeTmbTwo', mysql.TIME(fsp=6), nullable=True),
    sa.Column('TmbTwo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NamaKebun', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Divisi', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('JumlahJanjang', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NamaPT', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TotalPot', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BJR', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('JenisTbs', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lokasi_timbang', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tgltransaksione', 'ttbsdalam', ['TglTransaksiOne'], unique=False)
    op.create_index('idx_tgltransaksi_tbsdalam', 'ttbsdalam', ['TglTransaksiOne'], unique=False)
    op.create_index('idx_tgltransaksi_namakebun', 'ttbsdalam', ['TglTransaksiOne', 'NamaKebun'], unique=False)
    op.create_index('idx_namakebun_tbsdalam', 'ttbsdalam', ['NamaKebun'], unique=False)
    op.create_table('mlokasi',
    sa.Column('id_lokasi', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kode_lokasi', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nama_lokasi', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('distrik', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipe', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('alamat', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('keterangan', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_lokasi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('kode_lokasi', 'mlokasi', ['kode_lokasi'], unique=True)
    op.create_table('ttranslintas',
    sa.Column('NoTransaksi', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('NoDO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaProduk', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TglTmb1', sa.DATE(), nullable=True),
    sa.Column('TimeTmb1', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TglTmb2', sa.DATE(), nullable=True),
    sa.Column('TimeTmb2', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Terkirim', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Diterima', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sisa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Transportir', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PlatNo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaDriver', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoSurat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TglSurat', sa.DATE(), nullable=True),
    sa.Column('Ket', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_lokasi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Tujuan', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ttranspemasaran',
    sa.Column('NoTransaksi', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('NoDO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaProduk', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TglTmb1', sa.DATE(), nullable=True),
    sa.Column('TimeTmb1', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TglTmb2', sa.DATE(), nullable=True),
    sa.Column('TimeTmb2', mysql.TIME(fsp=6), nullable=True),
    sa.Column('Tmb2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Terkirim', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Diterima', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sisa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Transportir', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PlatNO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NamaDriver', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BeratTarra', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KadarKotoran', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('KadarAir', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Moisture', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('FFA', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('IV', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('SUHU', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoTangki', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoSegel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('JmlSegel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoBlangko', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Pemeriksa', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Asal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Tujuan', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoRef', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TotalTmb', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('StatusSambungDO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NoSambungDO', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_lokasi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('NoTransaksi'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ttranspemasaran_tgltmb1', 'ttranspemasaran', ['TglTmb1'], unique=False)
    op.drop_index(op.f('ix_TTransPemasaran_NoTransaksi'), table_name='TTransPemasaran')
    op.drop_table('TTransPemasaran')
    op.drop_index(op.f('ix_TTransLintasKeluar_NoTransaksi'), table_name='TTransLintasKeluar')
    op.drop_table('TTransLintasKeluar')
    op.drop_index(op.f('ix_TTransLintas_NoTransaksi'), table_name='TTransLintas')
    op.drop_table('TTransLintas')
    op.drop_index(op.f('ix_TTbsDalam_NoTransaksi'), table_name='TTbsDalam')
    op.drop_table('TTbsDalam')
    op.drop_table('MLokasi')
    # ### end Alembic commands ###
