from sqlalchemy import Column, String, Integer, Float, Date, Time
from app.core.database import Base

class TTransPemasaran(Base):
    __tablename__ = "TTransPemasaran"

    NoTransaksi = Column(String(50), primary_key=True, index=True)
    NoDO = Column(String(50))
    NamaProduk = Column(String(50))
    TglTmb1 = Column(Date)
    TimeTmb1 = Column(Time)
    Tmb1 = Column(Float)
    TglTmb2 = Column(Date)
    TimeTmb2 = Column(Time)
    Tmb2 = Column(Float)
    Qty = Column(Float)
    Terkirim = Column(Float)
    Diterima = Column(Float)
    Sisa = Column(Float)
    Transportir = Column(String(100))
    PlatNO = Column(String(20))
    NamaDriver = Column(String(50))
    BeratTarra = Column(Float)
    KadarKotoran = Column(Float)
    KadarAir = Column(Float)
    Moisture = Column(Float)
    FFA = Column(Float)
    IV = Column(Float)
    SUHU = Column(Float)
    NoTangki = Column(String(30))
    NoSegel = Column(String(50))
    JmlSegel = Column(Integer)
    NoBlangko = Column(String(50))
    Pemeriksa = Column(String(50))
    Status = Column(Integer)
    Asal = Column(String(100))
    Tujuan = Column(String(100))
    NoRef = Column(String(100))
    TotalTmb = Column(Float)
    StatusSambungDO = Column(String(50))
    NoSambungDO = Column(String(50))
    id_lokasi = Column(Integer)
